language: generic

sudo: required 

services:
  - docker

before_install:
  - docker build -t se7s/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true se7s/complex npm run test

after_success:
  - docker build -t 571998/multi-docker:client ./client
  - docker build -t 571998/multi-docker:nginx ./nginx
  - docker build -t 571998/multi-docker:server ./server
  - docker build -t 571998/multi-docker:worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push 571998/multi-docker:client
  - docker push 571998/multi-docker:nginx
  - docker push 571998/multi-docker:server
  - docker push 571998/multi-docker:worker